language: "en-US"

reviews:
  profile: "assertive"

  high_level_summary: true

  poem: false

  review_status: true

  collapse_walkthrough: false

chat:
  auto_reply: true

knowledge_base:
  learnings:
    scope: auto

early_access: false