openapi: 3.0.3
info:
  title: 'Laravel REST API with PEST Tests'
  description: 'API documentation for the Laravel REST API project with Sanctum authentication and PEST tests.'
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/projects:
    get:
      summary: 'GET /api/projects'
      operationId: gETapiprojects
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    post:
      summary: ''
      operationId: postApiProjects
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: wcyotcybfinsbzlihra
                  nullable: false
                description:
                  type: string
                  description: ''
                  example: 'Blanditiis exercitationem dicta non et.'
                  nullable: true
              required:
                - name
      security: []
  '/api/projects/{id}':
    get:
      summary: 'GET /api/projects/{project}'
      operationId: gETapiprojectsproject
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    put:
      summary: ''
      operationId: putApiProjectsId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: yhktoayov
                  nullable: false
                description:
                  type: string
                  description: ''
                  example: 'Soluta laudantium esse minima.'
                  nullable: true
              required:
                - name
      security: []
    delete:
      summary: ''
      operationId: deleteApiProjectsId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the project.'
        example: 4
        required: true
        schema:
          type: integer
  '/api/projects/{project_id}/tasks':
    get:
      summary: ''
      operationId: getApiProjectsProject_idTasks
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    post:
      summary: ''
      operationId: postApiProjectsProject_idTasks
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: bvlhtr
                  nullable: false
                description:
                  type: string
                  description: ''
                  example: 'Quod quidem aut consequatur beatae vel.'
                  nullable: true
                status:
                  type: string
                  description: ''
                  example: completed
                  nullable: false
                  enum:
                    - pending
                    - in-progress
                    - completed
                due_date:
                  type: string
                  description: 'Must be a valid date.'
                  example: '2026-07-10T12:16:37'
                  nullable: true
              required:
                - name
                - status
      security: []
    parameters:
      -
        in: path
        name: project_id
        description: 'The ID of the project.'
        example: 4
        required: true
        schema:
          type: integer
  '/api/tasks/{id}':
    get:
      summary: ''
      operationId: getApiTasksId
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    put:
      summary: ''
      operationId: putApiTasksId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: iuufhjvlrdvkjjqhhwcxwizd
                  nullable: false
                description:
                  type: string
                  description: ''
                  example: 'Id sint aut ea fugiat.'
                  nullable: true
                status:
                  type: string
                  description: ''
                  example: completed
                  nullable: false
                  enum:
                    - pending
                    - in_progress
                    - completed
                due_date:
                  type: string
                  description: 'Must be a valid date.'
                  example: '2026-07-10T12:16:37'
                  nullable: true
              required:
                - name
                - status
      security: []
    delete:
      summary: ''
      operationId: deleteApiTasksId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the task.'
        example: 1
        required: true
        schema:
          type: integer
  '/api/tasks/{id}/assign':
    post:
      summary: ''
      operationId: postApiTasksIdAssign
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                  description: 'The <code>id</code> of an existing record in the users table.'
                  example: ex
                  nullable: false
              required:
                - user_id
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the task.'
        example: 1
        required: true
        schema:
          type: integer
  /api/user:
    get:
      summary: ''
      operationId: getApiUser
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
tags:
  -
    name: Endpoints
    description: ''
