name: Laravel CI

on:
  push:
    branches:
      - master
      - develop
      - "feature/**"

  pull_request:
    branches:
      - master
      - develop

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          coverage: none

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Set Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Create SQLite Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Run Laravel Pint
        run: ./vendor/bin/pint --test

      - name: Run PHPStan (Larastan)
        run: ./vendor/bin/phpstan analyse

      - name: Run Pest Tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: ./vendor/bin/pest